/***** FILE GENERATED BY SCSS-PLUGIN FOR VITE *****/
  
/***** BASE IMPORTS *****/
import classNames from "classnames";
import React from "react";

/***** TYPE DEFINITIONS *****/
type TStyledMyComponentProps = React.CSSProperties & {
  "--background-color"?: string;
  "--color"?: string;
  "--padding"?: string;
};

type TClassNames = 
  | "MyComponent"
  | "MyComponent__test"
  | "MyComponent__test2"
  | "MyComponent__myComponent"
  | "MyComponent--test"

type TClassNamesObject = {
  [key in TClassNames]?: boolean;
}

type TStyledMyComponent = (args: TStyledMyComponentProps, className?: TClassNamesObject | TClassNames) => { 
  style: React.CSSProperties, 
  className: string
};

/***** STYLED FUNCTION *****/
//@ts-ignore
export const styleMyComponent: TStyledMyComponent = (style, className = "MyComponent") => ({ 
  style, 
  //@ts-ignore
  className: typeof className === 'object' ? classNames(className) : className
});
