/***** FILE GENERATED BY SCSS-PLUGIN FOR VITE *****/
  
/***** BASE IMPORTS *****/
import React from "react";

/***** TYPE DEFINITIONS *****/
type TStyledMyComponentProps = React.CSSProperties & {
  "--background-color"?: string;
  "--color"?: string;
  "--padding"?: string;
};
type TStyledMyComponent = (args: TStyledMyComponentProps) => [React.CSSProperties, typeof bemBuilder];
type TElement = 
  | "test"
  | "test2"
  | "myComponent"

const bemBuilder = Object.assign((element?: TElement) => {
  if (!element) {
    return "MyComponent";
  }

  return "MyComponent" + "__" + element;
}, {
  className: "MyComponent",
});

/***** STYLED FUNCTION *****/
export const styledMyComponent: TStyledMyComponent = (styles) => [styles, bemBuilder];
