// kawaii-scss-vars-plugin.js

import fs from 'fs';
import path from 'path';
import sass from 'sass';

function extractCssVariables(content) {
  // UwU Here, we're using a regex to find CSS variables in the SCSS content!
  const regex = /(--[a-zA-Z0-9_-]+)\s*:/g;
  const matches = content.matchAll(regex);
  const variables = {};

  for (const match of matches) {
    const variableName = match[1];
    variables[variableName] = ''; // You can put a default value or leave it empty~
  }

  return variables;
}

function extractFirstCssClassName(content) {
  // UwU Here, we're using a regex to find the first CSS class name in the SCSS content!
  const regex = /\.([a-zA-Z0-9_-]+)/;
  const matches = content.match(regex);

  return matches ? matches[1] : '';
}

/**
 * Extract all class names from the CSS content
 */
function extractAllClassNames(content) {
  const regex = /\.([\w-]+)/g;
  const matches = content.matchAll(regex);
  const classNames = [];

  for (const match of matches) {
    const className = match[1];

    // skip if there was a number before or after the dot
    if (/^\d+\.\d+$/.test(className)) {
      continue;
    }

    // skip if the class name is a number (since classnames cannot be numbers)
    if (!isNaN(Number(className))) {
      continue;
    }

    // skip if the class name is a unit (e.g. 1px, 2em, 3rem, etc.)
    if (/(em|px|rem|vh|vw|ch|ex|cm|mm|in|pt|pc|vmin|vmax|deg|grad|rad|turn|s|ms|Hz|kHz|%|fr|dpi|dpcm|dppx)$/.test(className)) {
      continue;
    }

    classNames.push(className.replace('.', ''));
  }

  return classNames;
}

function generateFunction(variables, fileName, className = '', allClassnames = []) {
  const typeName = `TStyled${fileName}`;

  const content = `
/***** FILE GENERATED BY SCSS-PLUGIN FOR VITE *****/
  
/***** BASE IMPORTS *****/
import classNames from "classnames";
import React from "react";

/***** TYPE DEFINITIONS *****/
type ${typeName}Props = React.CSSProperties & {
  ${Object.keys(variables).map((variable) => `"${variable}"?: string;`).join('\n  ')}
};

type TClassNames = \n  | ${[...new Set(allClassnames)].map((element) => `"${element}"`).join('\n  | ')}

type TClassNamesObject = {
  [key in TClassNames]?: boolean;
}

type ${typeName} = (args: ${typeName}Props, className?: TClassNamesObject | TClassNames) => { 
  style: React.CSSProperties, 
  className: string
};

/***** STYLED FUNCTION *****/
//@ts-ignore
export const style${fileName}: ${typeName} = (style, className = "${className}") => ({ 
  style, 
  //@ts-ignore
  className: typeof className === 'object' ? classNames(className) : className
});
  `.trim() + '\n';

  return content;
}

export function kawaiiScssVarsPlugin() {
  return {
    name: 'kawaii-scss-vars-plugin',
    // UwU The transform hook allows us to modify the content of each file!
    async transform(code, id) {
      if (id.endsWith('.scss')) {
        const result = sass.renderSync({ data: code }); // Compile SCSS to CSS
        const variables = extractCssVariables(result.css.toString());
        const className = extractFirstCssClassName(result.css.toString());
        const AllClassnames = extractAllClassNames(result.css.toString());

        console.log(className)

        const directory = path.dirname(id);
        const functionName = 'applyStyles'; // You can change this if you want!
        const fileName = id
          .replace('.scss', '')
          .split('/')
          .pop()
          .replace(/^_/, '');

        const functionContent = generateFunction(variables, fileName, className, AllClassnames);
        const outputFile = path.join(directory, `${functionName}.ts`);

        fs.writeFileSync(outputFile, functionContent); // Write the function file

        // UwU We return the modified code without any changes~
        return {
          code,
          map: null,
        };
      }
    },
  };
}
