/***** FILE GENERATED BY SCSS-PLUGIN FOR VITE *****/
  
/***** BASE IMPORTS *****/
import React from "react";

/***** TYPE DEFINITIONS *****/
type TStyledAppProps = React.CSSProperties & {
  "--test"?: string;
};
type TStyledApp = (args: TStyledAppProps) => [React.CSSProperties, typeof bemBuilder];
type TElement = 
  | 

const bemBuilder = Object.assign((element?: TElement) => {
  if (!element) {
    return "logo";
  }

  return "logo" + "__" + element;
}, {
  className: "logo",
});

/***** STYLED FUNCTION *****/
export const styledApp: TStyledApp = (styles) => [styles, bemBuilder];
